package image

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/pkg/errors"
	"github.com/sirupsen/logrus"
	"k8s.io/apimachinery/pkg/util/validation/field"
	"sigs.k8s.io/yaml"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/agent/manifests/staticnetworkconfig"
	"github.com/openshift/installer/pkg/types/imagebased"
	"github.com/openshift/installer/pkg/validate"
)

var configFilename = "imagebased-installation-config.yaml"

// ImageBasedInstallationConfig reads the imagebased-installation-config.yaml file.
type ImageBasedInstallationConfig struct { // nolint:revive // although this name stutters it is useful to convey that it's an image-based installer related struct
	File     *asset.File
	Config   *imagebased.InstallationConfig
	Template string
}

var _ asset.WritableAsset = (*ImageBasedInstallationConfig)(nil)

// Name returns a human friendly name for the asset.
func (*ImageBasedInstallationConfig) Name() string {
	return "Image-based Installation ISO Config"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*ImageBasedInstallationConfig) Dependencies() []asset.Asset {
	return []asset.Asset{}
}

// Generate generates the Image-based Installation Config YAML manifest.
func (i *ImageBasedInstallationConfig) Generate(dependencies asset.Parents) error {
	configTemplate := `#
# Note: This is a sample ImageBasedInstallationConfig file showing
# which fields are available to aid you in creating your
# own imagebased-installation-config.yaml file.
#
apiVersion: v1beta1
kind: ImageBasedInstallationConfig
metadata:
  name: example-imagebased-installation-config
seedImage: quay.io/openshift-kni/seed-image:4.16.0
seedVersion: 4.16.0
installationDisk: /dev/vda
useContainersFolder: false
precacheBestEffort: false
precacheDisabled: false
pullSecret: '<your-pull-secret>'
networkConfig:
  interfaces:
    - name: eth0
      type: ethernet
      state: up
      mac-address: 00:00:00:00:00:00
      ipv4:
        enabled: true
        address:
          - ip: 192.168.122.2
            prefix-length: 23
        dhcp: false
`

	i.Template = configTemplate

	// Set the File field correctly with the generated image-based installation config YAML content.
	i.File = &asset.File{
		Filename: configFilename,
		Data:     []byte(i.Template),
	}

	return nil
}

// PersistToFile writes the imagebased-installation-config.yaml file to the assets folder.
func (i *ImageBasedInstallationConfig) PersistToFile(directory string) error {
	templatePath := filepath.Join(directory, configFilename)
	templateByte := []byte(i.Template)

	err := os.WriteFile(templatePath, templateByte, 0o600)
	if err != nil {
		return err
	}

	return nil
}

// Files returns the files generated by the asset.
func (i *ImageBasedInstallationConfig) Files() []*asset.File {
	if i.File != nil {
		return []*asset.File{i.File}
	}
	return []*asset.File{}
}

// Load returns image-based installation ISO config asset from the disk.
func (i *ImageBasedInstallationConfig) Load(f asset.FileFetcher) (bool, error) {
	file, err := f.FetchByName(configFilename)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, errors.Wrap(err, fmt.Sprintf("failed to load %s file", configFilename))
	}
	config := &imagebased.InstallationConfig{}
	if err := yaml.UnmarshalStrict(file.Data, config); err != nil {
		return false, errors.Wrapf(err, "failed to unmarshal %s", configFilename)
	}

	i.File, i.Config = file, config
	if err = i.finish(); err != nil {
		return false, err
	}
	return true, nil
}

func (i *ImageBasedInstallationConfig) finish() error {
	if err := i.validate().ToAggregate(); err != nil {
		return errors.Wrapf(err, "invalid Image-based Installation ISO Config")
	}
	return nil
}

func (i *ImageBasedInstallationConfig) validate() field.ErrorList {
	var allErrs field.ErrorList

	if err := i.validatePullSecret(); err != nil {
		allErrs = append(allErrs, err...)
	}
	if err := i.validateSSHKey(); err != nil {
		allErrs = append(allErrs, err...)
	}
	if err := i.validateSeedImage(); err != nil {
		allErrs = append(allErrs, err...)
	}
	if err := i.validateSeedVersion(); err != nil {
		allErrs = append(allErrs, err...)
	}
	if err := i.validateInstallationDisk(); err != nil {
		allErrs = append(allErrs, err...)
	}
	if err := i.validateAdditionalTrustBundle(); err != nil {
		allErrs = append(allErrs, err...)
	}
	if err := i.validateNetworkConfig(); err != nil {
		allErrs = append(allErrs, err...)
	}

	return allErrs
}

func (i *ImageBasedInstallationConfig) validatePullSecret() field.ErrorList {
	var allErrs field.ErrorList

	pullSecretPath := field.NewPath("pullSecret")

	if i.Config.PullSecret == "" {
		allErrs = append(allErrs, field.Required(pullSecretPath, "you must specify a pullSecret"))
		return allErrs
	}

	if err := validate.ImagePullSecret(i.Config.PullSecret); err != nil {
		allErrs = append(allErrs, field.Invalid(pullSecretPath, i.Config.PullSecret, err.Error()))
	}

	return allErrs
}

func (i *ImageBasedInstallationConfig) validateSSHKey() field.ErrorList {
	var allErrs field.ErrorList

	sshKeyPath := field.NewPath("sshKey")

	// empty SSHKey is fine
	if i.Config.SSHKey == "" {
		return nil
	}

	if err := validate.SSHPublicKey(i.Config.SSHKey); err != nil {
		allErrs = append(allErrs, field.Invalid(sshKeyPath, i.Config.SSHKey, err.Error()))
	}

	return allErrs
}

func (i *ImageBasedInstallationConfig) validateAdditionalTrustBundle() field.ErrorList {
	var allErrs field.ErrorList

	additionalTrustBundlePath := field.NewPath("additionalTrustBundle")

	// empty AdditionalTrustBundle is fine
	if i.Config.AdditionalTrustBundle == "" {
		return nil
	}

	if err := validate.CABundle(i.Config.AdditionalTrustBundle); err != nil {
		allErrs = append(allErrs, field.Invalid(additionalTrustBundlePath, i.Config.AdditionalTrustBundle, err.Error()))
	}

	return allErrs
}

func (i *ImageBasedInstallationConfig) validateSeedImage() field.ErrorList {
	var allErrs field.ErrorList

	seedImagePath := field.NewPath("seedImage")

	if i.Config.SeedImage == "" {
		allErrs = append(allErrs, field.Required(seedImagePath, "you must specify a seedImage"))
	}

	return allErrs
}

func (i *ImageBasedInstallationConfig) validateSeedVersion() field.ErrorList {
	var allErrs field.ErrorList

	seedVersionPath := field.NewPath("seedVersion")

	if i.Config.SeedVersion == "" {
		allErrs = append(allErrs, field.Required(seedVersionPath, "you must specify a seedVersion"))
	}

	return allErrs
}

func (i *ImageBasedInstallationConfig) validateInstallationDisk() field.ErrorList {
	var allErrs field.ErrorList

	installationDiskPath := field.NewPath("installationDisk")

	if i.Config.InstallationDisk == "" {
		allErrs = append(allErrs, field.Required(installationDiskPath, "you must specify an installationDisk"))
	}

	return allErrs
}

func (i *ImageBasedInstallationConfig) validateNetworkConfig() field.ErrorList {
	var allErrs field.ErrorList

	networkConfig := field.NewPath("networkConfig")

	staticNetworkConfigGenerator := staticnetworkconfig.New(logrus.StandardLogger(), staticnetworkconfig.Config{MaxConcurrentGenerations: 2})

	// empty NetworkConfig is fine
	if i.Config.NetworkConfig.String() == "" {
		return nil
	}

	// Validate the network config using nmstatectl.
	if err := staticNetworkConfigGenerator.ValidateNMStateYaml(context.Background(), i.Config.NetworkConfig.String()); err != nil {
		allErrs = append(allErrs, field.Invalid(networkConfig, i.Config.NetworkConfig, err.Error()))
	}

	return allErrs
}
